/**
 * TextMagic API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TextmagicClient) {
      root.TextmagicClient = {};
    }
    root.TextmagicClient.ImportColumnMappingItem = factory(root.TextmagicClient.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ImportColumnMappingItem model module.
   * @module model/ImportColumnMappingItem
   * @version 2.0.615
   */

  /**
   * Constructs a new <code>ImportColumnMappingItem</code>.
   * @alias module:model/ImportColumnMappingItem
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>ImportColumnMappingItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ImportColumnMappingItem} obj Optional instance to populate.
   * @return {module:model/ImportColumnMappingItem} The populated <code>ImportColumnMappingItem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('column_position_in_file')) {
        obj['column_position_in_file'] = ApiClient.convertToType(data['column_position_in_file'], 'String');
      }
      if (data.hasOwnProperty('field_or_custom_field_id')) {
        obj['field_or_custom_field_id'] = ApiClient.convertToType(data['field_or_custom_field_id'], 'String');
      }
    }
    return obj;
  }

  /**
   * Column position in file (indexed from 0)
   * @member {String} column_position_in_file
   */
  exports.prototype['column_position_in_file'] = undefined;
  /**
   * Field or custom field id
   * @member {String} field_or_custom_field_id
   */
  exports.prototype['field_or_custom_field_id'] = undefined;



  return exports;
}));


