/**
 * TextMagic API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2
 * Contact: support@textmagi.biz
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.8
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TextmagicClient);
  }
}(this, function(expect, TextmagicClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TextmagicClient.ForwardedCall();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ForwardedCall', function() {
    it('should create an instance of ForwardedCall', function() {
      // uncomment below and update the code to test ForwardedCall
      //var instance = new TextmagicClient.ForwardedCall();
      //expect(instance).to.be.a(TextmagicClient.ForwardedCall);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new TextmagicClient.ForwardedCall();
      //expect(instance).to.be();
    });

    it('should have the property callTime (base name: "callTime")', function() {
      // uncomment below and update the code to test the property callTime
      //var instance = new TextmagicClient.ForwardedCall();
      //expect(instance).to.be();
    });

    it('should have the property caller (base name: "caller")', function() {
      // uncomment below and update the code to test the property caller
      //var instance = new TextmagicClient.ForwardedCall();
      //expect(instance).to.be();
    });

    it('should have the property via (base name: "via")', function() {
      // uncomment below and update the code to test the property via
      //var instance = new TextmagicClient.ForwardedCall();
      //expect(instance).to.be();
    });

    it('should have the property receiver (base name: "receiver")', function() {
      // uncomment below and update the code to test the property receiver
      //var instance = new TextmagicClient.ForwardedCall();
      //expect(instance).to.be();
    });

  });

}));
